/**
 * Pulls the SDK documentation a given setup run will actually need, and writes
 * it into the repo next to `shipeasy-wiring.md`.
 *
 * Why this exists: the wiring instructions are generated by whatever CLI
 * version happens to be installed, but the *docs* are served live from each SDK
 * repo's GitHub Pages. Fetching the pages that match THIS run's answers — the
 * devtools surface, the feature modules, whether anything serves a page — means
 * a stale CLI still hands the agent current, version-correct wiring. Fixing a
 * wrong install snippet becomes an SDK-repo doc edit, not a CLI release.
 *
 * Two knobs decide what gets pulled:
 *
 *  - the **topics** this run selected (below), and
 *  - each topic's **handles** — the doc pages that answer it. An SDK repo can
 *    override or extend a topic's handles from its own `manifest.json`
 *    (`setup: { devtools: ["browser-devtools", …] }`), so a renamed or newly
 *    split page reaches customers without touching this file.
 *
 * Only handles the SDK's manifest actually publishes are fetched; anything else
 * is reported as missing rather than written as a 404.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { customOperations } from "@shipeasy/openapi/custom";
import { fetchSdkDoc } from "./sdk-docs";

/** Folder (repo-root-relative) the pulled pages land in. Paired with `shipeasy-wiring.md`. */
export const DOCS_DIRNAME = "shipeasy-wiring-docs";

const docsListOp = customOperations.find((o) => o.group[0] === "docs" && o.name === "list");

/** A setup topic — one wiring concern, answered by one (or a few) doc pages. */
export type DocTopic =
  | "installation"
  | "configuration"
  | "head-tags"
  | "browser-devtools"
  | "react-native-devtools"
  | "flags"
  | "configs"
  | "killswitches"
  | "experiments"
  | "metrics"
  | "error-reporting"
  | "i18n";

interface TopicSpec {
  /** Human title for the reference index in the wiring doc. */
  title: string;
  /** What the agent needs it FOR — rendered next to the path. */
  why: string;
  /**
   * Candidate doc handles, best first. Tried in order against what the SDK
   * publishes; the first hit wins. Aliases are deliberate — SDKs that split or
   * rename a page still resolve without a CLI release.
   */
  handles: string[];
}

const TOPICS: Record<DocTopic, TopicSpec> = {
  installation: {
    title: "Installation",
    why: "install + the one `configure()`/`shipeasy()` call, with this language's exact imports",
    handles: ["installation", "install", "getting-started"],
  },
  configuration: {
    title: "Configuration & identity",
    why: "every option on the init call, and the identity/attributes transform the targeting step needs",
    handles: ["configuration", "config", "advanced"],
  },
  "head-tags": {
    title: "Script-tag helpers",
    why: "the SDK's own tag helpers (bootstrap / i18n / devtools) — never hand-template these",
    handles: ["advanced", "script-tags", "head-tags", "browser"],
  },
  "browser-devtools": {
    title: "Browser devtools overlay",
    why: "the overlay tag this SDK emits, its attributes, and how to gate it per build",
    handles: ["browser-devtools", "devtools"],
  },
  "react-native-devtools": {
    title: "React Native devtools overlay",
    why: "the `<ShipeasyDevtools />` mount, its props, and the deep-link scheme requirement",
    handles: ["react-native-devtools", "native-devtools"],
  },
  flags: {
    title: "Feature flags",
    why: "the gate-evaluation call — signature, async-ness, and the default when evaluation fails",
    handles: ["flags", "release/flags", "gates"],
  },
  configs: {
    title: "Dynamic configs",
    why: "reading a typed remote config, including the fallback value contract",
    handles: ["configs", "release/configs", "dynamic-configs"],
  },
  killswitches: {
    title: "Kill switches",
    why: "the one-flip off-switch read, and the sub-switch map",
    handles: ["killswitches", "release/killswitches", "kill-switches"],
  },
  experiments: {
    title: "Experiments",
    why: "getting a variant + the exposure semantics that make an experiment analysable",
    handles: ["experiments", "release/experiments"],
  },
  metrics: {
    title: "Event tracking",
    why: "the `track()` call that feeds metrics, experiment readouts, and alert rules",
    handles: ["metrics/track", "metrics", "tracking", "events"],
  },
  "error-reporting": {
    title: "Error reporting",
    why: "the `see()` grammar — the error primitive every catch block should use",
    handles: ["error-reporting", "ops/see", "errors"],
  },
  i18n: {
    title: "Translations (i18n)",
    why: "the translate call + how strings reach this runtime",
    handles: ["i18n", "translations", "i18n/setup"],
  },
};

/** What this setup run turned on — the input the topic plan is derived from. */
export interface DocPlanInput {
  /** Distinct SDKs across the wired targets, with a framework hint for {{FRAMEWORK}}. */
  sdks: { sdk: string; framework?: string }[];
  /** Any non-native target renders HTML (or the user accepted the browser overlay). */
  servesPages: boolean;
  /** The user accepted the in-page overlay. */
  devtoolsBrowser: boolean;
  /** The user accepted the React Native overlay. */
  devtoolsNative: boolean;
  /** Module groups enabled server-side this run (`flags` / `ops` / `i18n`). */
  features: string[];
}

/**
 * The topics this run needs, in reading order. `installation` and
 * `configuration` are unconditional — every wiring run installs the SDK and
 * every run has to wire identity, so those two are never a judgement call.
 */
export function planTopics(input: DocPlanInput): DocTopic[] {
  const topics: DocTopic[] = ["installation", "configuration"];
  if (input.servesPages) topics.push("head-tags");
  if (input.devtoolsBrowser) topics.push("browser-devtools");
  if (input.devtoolsNative) topics.push("react-native-devtools");
  if (input.features.includes("flags")) {
    topics.push("flags", "configs", "killswitches", "experiments", "metrics");
  }
  if (input.features.includes("ops")) topics.push("error-reporting");
  if (input.features.includes("i18n")) topics.push("i18n");
  return topics;
}

/** What an SDK publishes, as `docs list` reports it. */
export interface DocIndex {
  pages: string[];
  snippets: Record<string, string[]>;
  /** The SDK repo's own topic → handles overrides. */
  setup: Record<string, string[]>;
  /** True when the repo has no manifest and the built-in default set is standing in. */
  fallback: boolean;
}

async function loadIndex(sdk: string): Promise<DocIndex | null> {
  if (!docsListOp) return null;
  try {
    const r = (await docsListOp.run({ sdk })) as Partial<DocIndex>;
    return {
      pages: r.pages ?? [],
      snippets: r.snippets ?? {},
      setup: r.setup ?? {},
      fallback: Boolean(r.fallback),
    };
  } catch {
    return null;
  }
}

/** Does this SDK publish `handle` — either a page key or a `group/resource` snippet? */
function publishes(idx: DocIndex, handle: string): boolean {
  if (handle.includes("/")) {
    const [group, resource] = handle.split("/", 2);
    return (idx.snippets[group] ?? []).includes(resource);
  }
  return idx.pages.includes(handle);
}

/**
 * The handle to fetch for `topic`, or null when this SDK publishes none of the
 * candidates. The SDK's own `setup` map is consulted first so a repo can point a
 * topic at a page this CLI has never heard of.
 */
export function resolveHandle(idx: DocIndex, topic: DocTopic): string | null {
  const candidates = [...(idx.setup[topic] ?? []), ...TOPICS[topic].handles];
  return candidates.find((h) => publishes(idx, h)) ?? null;
}

/** One pulled page. */
export interface BundledDoc {
  sdk: string;
  topic: DocTopic;
  /** The doc handle it resolved to (what `shipeasy docs get` would take). */
  handle: string;
  title: string;
  why: string;
  /** Repo-root-relative path it is written to. */
  file: string;
  /** The page body as published. */
  content: string;
}

export interface DocBundle {
  /** Repo-root-relative folder holding every page. */
  dir: string;
  docs: BundledDoc[];
  /** Topics an SDK publishes nothing for — the wiring doc says so rather than pretending. */
  missing: { sdk: string; topic: DocTopic }[];
}

/**
 * The bundle as the wiring doc consumes it — paths and blurbs, no page bodies.
 * They are the current published pages, fetched minutes ago, which is the point:
 * a CLI that has gone stale still hands the agent wiring that matches the SDK as
 * it ships today.
 */
export interface ReferenceDocs {
  /** Repo-root-relative folder holding the pages. */
  dir: string;
  pages: { sdk: string; topic: DocTopic; title: string; why: string; file: string }[];
  /** Topics whose SDK publishes no page — named so the agent knows to look elsewhere. */
  missing: { sdk: string; topic: DocTopic }[];
}

/** Drop the page bodies; keep what the wiring doc links to. */
export function toReferenceDocs(bundle: DocBundle): ReferenceDocs {
  return {
    dir: bundle.dir,
    pages: bundle.docs.map(({ sdk, topic, title, why, file }) => ({ sdk, topic, title, why, file })),
    missing: bundle.missing,
  };
}

/** The pulled page answering `topic` for `sdk`, or null when it wasn't pulled. */
export function docFile(
  refs: ReferenceDocs | undefined,
  sdk: string,
  topic: DocTopic,
): string | null {
  return refs?.pages.find((p) => p.sdk === sdk && p.topic === topic)?.file ?? null;
}

/**
 * Where to read `topic` for `sdk`: the page already on disk, or the command that
 * fetches it. Deliberately bare — that these pages outrank the wiring file is
 * stated once, in the index section, not re-litigated at every callsite.
 */
export function docPointer(
  refs: ReferenceDocs | undefined,
  sdk: string,
  topic: DocTopic,
  handle: string,
): string {
  const file = docFile(refs, sdk, topic);
  return file ? `\`${file}\`` : `\`shipeasy docs get --sdk ${sdk} ${handle}\``;
}

/**
 * Resolve + fetch every planned topic for every SDK in the run. Pure network —
 * `writeDocBundle` does the disk half, so a dry run can preview the plan.
 */
export async function fetchDocBundle(input: DocPlanInput): Promise<DocBundle> {
  const topics = planTopics(input);
  const docs: BundledDoc[] = [];
  const missing: { sdk: string; topic: DocTopic }[] = [];
  const seen = new Set<string>();
  for (const { sdk, framework } of input.sdks) {
    if (seen.has(sdk)) continue;
    seen.add(sdk);
    const idx = await loadIndex(sdk);
    for (const topic of topics) {
      const handle = idx ? resolveHandle(idx, topic) : TOPICS[topic].handles[0];
      if (!handle) {
        missing.push({ sdk, topic });
        continue;
      }
      const content = await fetchSdkDoc(sdk, handle, framework);
      if (!content?.trim()) {
        missing.push({ sdk, topic });
        continue;
      }
      docs.push({
        sdk,
        topic,
        handle,
        title: TOPICS[topic].title,
        why: TOPICS[topic].why,
        file: `${DOCS_DIRNAME}/${sdk}/${topic}.md`,
        content,
      });
    }
  }
  return { dir: DOCS_DIRNAME, docs, missing };
}

/**
 * Write a fetched bundle under `<root>/shipeasy-wiring-docs/`. Each page keeps a
 * provenance header so a reader (human or agent) knows it is a snapshot and how
 * to re-pull it.
 */
export function writeDocBundle(root: string, bundle: DocBundle): DocBundle {
  for (const d of bundle.docs) {
    const path = join(root, d.file);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(
      path,
      `<!-- Pulled by \`shipeasy setup\` from the ${d.sdk} SDK's published docs (handle: ${d.handle}).\n` +
        `     This is the LATEST published page as of setup — it wins over anything the\n` +
        `     wiring file or your own memory says. Re-pull: shipeasy docs get --sdk ${d.sdk} ${d.handle} -->\n\n` +
        `${d.content.trim()}\n`,
      "utf8",
    );
  }
  return bundle;
}
